version: '3.4'

services:
  samba:
    image: dperson/samba:armhf
    container_name: samba
    network_mode: host
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - /docker/samba:/mnt
    command: '-n  -w "WORKGROUP" -g "guest account = nobody" -g "netbios name = raspberrypi" -g "map to guest = Bad User"  -g "server min protocol = SMB3"  -g "map to guest = Bad User" -s "PUBLIC;/mnt;yes;no;yes;"'

  wsdd:
    image: mohankumargupta/wsdd
    container_name: wsdd
    network_mode: host
    command: ["-n raspberrypi","-4","-p"]
    ports:
      - "3702:3702/udp"
      - "5357:5357"      
