version: '3.4'

services:
  portainer:
    image: portainer/portainer:linux-arm
    container_name: portainer
    command: --no-auth
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  samba:
    image: dperson/samba:armhf
    container_name: samba
    network_mode: host
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - /docker/samba:/mnt
    command: '-n  -w "WORKGROUP" -g "guest account = nobody" -g "netbios name = mohan" -g "map to guest = Bad User"  -g "server min protocol = SMB3"  -g "map to guest = Bad User" -s "PUBLIC;/mnt;yes;no;yes;"'


  wsdd:
    image: python:alpine
    container_name: wsdd
    

  grafana:
    image: grafana/grafana:6.2.5
    command: cfg:default.users.allow_sign_up=false
    network_mode: host
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,briangann-gauge-panel
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_ROLE="Editor"
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_ADMIN_PASSWORD=password

  timeseriesadmin:
    image: mohankumargupta/timeseriesadmin
    container_name: timeseriesadmin
    ports:
      - "8085:80"
     
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "8080:80"
    volumes:
      - /docker/nginx:/usr/share/nginx/html:ro



  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"


 
